name: devops-test-felmo
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy HTML
        uses: appleboy/ssh-action@v0.1.2
        with:
            host: ${{secrets.DEVOPS_CASESTUDY_HOST}}
            key: ${{secrets.GHUB_DEPLOY_USER_PRIV}}
            username: ${{secrets.GHUB_DEPLOY_USER}}
          
            script: |
              if [ ! -d /home/ghub-deploy/devopstest ]; then mkdir devopstest; fi
              cd devopstest
              git clone https://github.com/kikeriffs/devopstest.git
              cp devopstest/index.html /var/www/html/index.html
